version: '2'
services:
  db:
    build:
      dockerfile: Dockerfile.mysql
      context: .
    env_file: .env
    volumes:
      - ./mysql-data/:/var/lib/mysql/
    ports:
      - "3306:3306"
  db-udf:
    build:
      dockerfile: Dockerfile.mysql-udf
      context: .
    environment:
      MYSQL_HOST: db
    env_file: .env
    depends_on:
      - db
  web:
    build:
      context: ./angular-rails-app/
    command: ["sh", "-c", "/angular-rails-app/docker-cmd.sh"]
    env_file: .env
    environment:
      MYSQL_HOST: db
    volumes:
      - ./angular-rails-app/:/angular-rails-app/
    ports:
      - "3000:3000"
    depends_on:
      - db
  nb:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    # 2G Limit
    mem_limit: 2147483648
    environment:
      MYSQL_HOST: db
    volumes:
      - ./JPF/:/root/JPF/
      - ./data-imports/:/root/data-imports/
      - ./data/:/root/heatseek/
    ports:
      - "8888:8888"
    depends_on:
      - db
    links:
      - db:db
